### ISSUE TITLE
Trademarks

### ISSUE THREAD

**Issue by firmai** [codingatty/Plumage#1]
Hi Terry, I would your professional opinion, I want to do something fairly simply but I have been hitting my head for 3 days now. I am looking for a means to search a brand or trademark like "Nike" and to then get a list of possible owners like "Nike, Inc". I can retrieve this information from the website https://tmsearch.uspto.gov/, but I have not idea what API to use 🤷

**Comment by codingatty** [comment]
The USPTO has two different mechanisms for trademark information: [Trademark Status Document and Retrieval](https://tsdr.uspto.gov/) (TSDR); and [Trademark Electronic Search System](https://tmsearch.uspto.gov) (TESS).

TSDR is for retrieving information about a known trademark;  TESS is for searching for unknown trademarks.

Plumage is in interface to TSDR, making it easier to programmatically pull information from it. It doesn't do anything about searching (which is the domain of TESS).

I've looked into doing some sort of new open source project for TESS, but it's not very straightforward. TESS has no published API, and each query made to it establishes a session that is re-used for subsequent searches. That approach makes it fairly powerful, in that it allows you to do multiple searches in that session and combine and subset them; but that same feature makes it difficult to access programmatically. On top of that, the data that's returned doesn't come back in any neat API-style form; you'd have to screen-scrape it with something like BeautifulSoup. That way madness lies.

I assume its _possible_, in that anything you can do with a browser is capable of being mimicked by a non-browser program, but it looks pretty inelegant, and I've not explored it in any detail.

I remember another guy working this, and because of the lack of a real API, his approach was to download the daily trademark database dumps (which are huge) and replicating them on his own system and searching that.

But the upshot is, Plumage is not going to have any search support, because that relates to a different USPTO system (TESS) that has no API.

By the way, you can find a list of what the USPTO considers APIs [here](https://developer.uspto.gov/api-catalog).
